function Hd = my_filter
%MY_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 14-Jan-2015 19:14:08

Fpass = 0.2;  % Passband Frequency
Fstop = 0.4;  % Stopband Frequency
Apass = 1;    % Passband Ripple (dB)
Astop = 41;   % Stopband Attenuation (dB)

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);

Hd = design(h, 'kaiserwin');



